Add missing argument in proxy style init
This adds PyQt v6.5 compatibility by fixing this error:

  TypeError: arguments did not match any overloaded call:
    QProxyStyle(style: typing.Optional[QStyle] = None): not enough arguments
    QProxyStyle(key: Optional[str]): not enough arguments